### ISSUE TITLE
client code is missing

### ISSUE THREAD

**Issue by slitvinov** [weymouth/WaterLily#1]
Is there a code for the simulation from a twit?
https://twitter.com/gabrielweymouth/status/1281979466319896576

**Comment by weymouth** [comment]
This was what I asked in the tweet. What is the accepted/normal place to put example files in a Julia repo?

**Comment by slitvinov** [comment]
Logically WaterLily looks like a library/package. A client code should use that package and it belongs to a separate package.  But maybe it is too much bureaucracy.

**Comment by saschatimme** [comment]
I also would like to play around with you example :) I think it would be completely fine to put it in an example folder for now.

**Comment by weymouth** [comment]
Twitter example https://github.com/weymouth/WaterLily/blob/master/examples/TwoD_block.jl
